language: ruby
rvm:
  # The version used at SLE12
  - 2.1.2

  # The version used at openSUSE 13.2
  - 2.1.3

  # Other Ruby Versions
  - 2.1.10
  - 2.2.4
  - 2.3.0

  # Future versions
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update --system

before_script:
  - bundle exec rake db:setup

script:
  - bundle exec rspec spec
  - bundle exec rubocop -V
  - bundle exec rubocop -F
  - bundle exec brakeman -z -A

addons:
  code_climate:
    repo_token: f6e3f94baf7a2d672fa17cd11deb8d3e0709be5350ad0dd11e33f44f54d540bd
  mariadb: '10.0'

after_success:
  - bundle exec codeclimate-test-reporter
