apiVersion: v1
kind: Pod
metadata:
  name: salt
  labels:
    name: salt
spec:
  hostNetwork: true
  containers:
  - name: salt-master
    image: opensuse/salt-master:boron
    volumeMounts:
    - mountPath: /etc/salt/master.d
      name: salt-master-config
    - mountPath: /srv/salt
      name: salt-master
    - mountPath: /var/run/salt/master
      name: salt-sock-dir
  - name: salt-api
    image: opensuse/salt-api:boron
    volumeMounts:
    - mountPath: /etc/salt/master.d
      name: salt-master-config
    - mountPath: /var/run/salt/master
      name: salt-sock-dir
  - name: salt-minion
    image: opensuse/salt-minion:boron
    volumeMounts:
    - mountPath: /etc/salt/minion.d
      name: salt-minion-config
  volumes:
    - name: salt-master-config
      hostPath:
        path: ${project_dir}/kubernetes/salt/config/master.d
    - name: salt-master
      hostPath:
        path: ${project_dir}/kubernetes/salt/salt
    - name: salt-sock-dir
      hostPath:
        path: ${project_dir}/kubernetes/tmp/salt-sock-dir
    - name: salt-minion-config
      hostPath:
        path: ${project_dir}/kubernetes/salt/config/minion.d
